### PR TITLE
Add section on scikit-image support

### PR DESCRIPTION
**Pull request by jni**
Comments and suggestions most welcome!

@stefanv @emmanuelle could you please review this?

@paugier I hope this suits! :smiley: 

Thanks!

### CODE REVIEW

**Comment by paugier** [comment]
Thanks a lot @jni ! This point of view really improves the proposal!

**Comment by emmanuelle** [comment]
Hey @jni, I find the text really well written, nothing to change on my end. Thanks!

**Comment by stefanv** [comment]
I sent you some minor comments on Zulip; overall looks great!

**Comment by paugier** [comment]
Hi @jni, do you want to modify your text ? Do I merge like that ?

**Comment by jni** [comment]
@paugier sorry for the delay, I just needed one more clarification, ready to merge now. =)

**Pull request merged**
